### ISSUE TITLE
Asking for name change

### ISSUE THREAD

**Issue by yufeih** [nine/email-validator#1]
Hi _nine_,

We tried to create an organization on github with the name _nine_ but unfortunately this name is already taken :(

As you can see, we have quite a few projects with the _nine_ branding, so we are hoping if there is a possibility to give us this name.

Thanks so much for your help!

**Comment by btittelbach** [comment]
mhh, nine's nickname is well known in various projects and I believe He's had it pretty much since the beginning of the Web in europe. Not sure I'd just give up my name like that....

**Comment by yufeih** [comment]
yeah, it is quite hard to give up, so I was just asking if there is a possibility.
